import pandas as pd
import plotly.express as px

# import plotly.offline as pyo


data = {
    "Candidate": [
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Anis Rouis",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
        "Jasser Boulila",
    ],
    "NumberofVoters": [
        1,
        2,
        5,
        6,
        8,
        9,
        20,
        10,
        12,
        13,
        14,
        15,
        20,
        10,
        12,
        13,
        14,
        15,
        20,
        10,
        12,
        13,
        14,
        15,
        20,
        10,
        12,
        13,
        14,
        15,
        2,
        4,
        10,
        12,
        19,
        20,
        1,
        2,
        5,
        6,
        8,
        9,
        20,
        10,
        12,
        13,
        14,
        15,
        20,
        10,
        1,
        2,
        5,
        6,
        8,
        9,
        20,
        10,
        12,
        13,
        14,
        15,
        20,
        10,
        12,
        13,
        14,
        15,
        20,
        10,
        12,
        13,
        14,
        15,
        20,
        10,
        12,
        13,
        14,
        15,
        2,
        4,
        10,
        12,
        19,
        20,
        1,
        2,
        5,
        6,
        8,
        9,
        20,
        10,
        12,
        13,
        14,
        15,
        20,
        10,
    ],  # Numeric values without '%' symbol
    "region": [
        "NewYork",
        "Alabama",
        "Tunis",
        "Hmed",
        "fhjsdk",
        "SDHJDHQS",
        "hmed",
        "Alaa",
        "Tis",
        "Hd",
        "fsdk",
        "SJDHQS",
        "Neork",
        "Alama",
        "Tis",
        "Hd",
        "fsk",
        "SDHQS",
        "qsdqs",
        "qsdqsd",
        "qsdqsd",
        "qsdqsdqsd",
        "fdf",
        "fg",
        "fgh",
        "ghj",
        "khjk",
        "rzedfcs",
        "gfdc",
        "fgdvf",
        "dfssfsd",
        "sdfsdf",
        "NewYork",
        "Alabama",
        "Tunis",
        "Hmed",
        "NewYork",
        "Alabama",
        "Tunis",
        "Hmed",
        "fhjsdk",
        "SDHJDHQS",
        "hmed",
        "Alaa",
        "Tis",
        "Hd",
        "fsdk",
        "SJDHQS",
        "Neork",
        "Alama",
        "Tis",
        "Hd",
        "fsk",
        "SDHQS",
        "qsdqs",
        "qsdqsd",
        "qsdqsd",
        "qsdqsdqsd",
        "fdf",
        "fg",
        "fgh",
        "ghj",
        "khjk",
        "rzedfcs",
        "gfdc",
        "fgdvf",
        "dfssfsd",
        "sdfsdf",
        "NewYork",
        "Alabama",
        "Tunis",
        "Hmed",
        "NewYork",
        "Alabama",
        "Tunis",
        "Hmed",
        "fhjsdk",
        "SDHJDHQS",
        "hmed",
        "Alaa",
        "Tis",
        "Hd",
        "fsdk",
        "SJDHQS",
        "Neork",
        "Alama",
        "Tis",
        "Hd",
        "fsk",
        "SDHQS",
        "qsdqs",
        "qsdqsd",
        "qsdqsd",
        "qsdqsdqsd",
        "fdf",
        "fg",
        "fgh",
        "ghj",
        "khjk",
        "rzedfcs",
    ],
}


# Convert to DataFrame
df = pd.DataFrame(data)
# Create the bar chart
fig = px.bar(df, x="Candidate", y="NumberofVoters", color="region", barmode="group")
# Save the figure as an HTML file
html_file_path = "plotly.html"
fig.write_html(html_file_path)
